# REUSE Software Bill of Materials
# https://reuse.software/
version = 1
SPDX-PackageName = "cookiecutter-python-template"
SPDX-PackageSupplier = "Byron Williams"
SPDX-PackageDownloadLocation = "https://github.com/ByronWilliamsCPA/cookiecutter-python-template"

[[annotations]]
path = ["**"]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "2025 Byron Williams"
