# ============================================================================
# Reusable Python Release Workflow
# ============================================================================
# This workflow should be placed in your organization's .github repository at:
#   .github/workflows/python-release.yml
#
# Projects call this workflow using:
#   uses: ORG/.github/.github/workflows/python-release.yml@main
#
# Features:
#   - Pre-release testing
#   - Semantic versioning with python-semantic-release
#   - Manual release mode (tag-based)
#   - PyPI publishing with OIDC trusted publishing
#   - GitHub Release creation
# ============================================================================

name: Reusable Python Release

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.12'
      coverage-threshold:
        description: 'Minimum code coverage percentage for pre-release tests'
        required: false
        type: number
        default: 80
      source-directory:
        description: 'Source code directory'
        required: false
        type: string
        default: 'src'
      semantic-release:
        description: 'Use semantic release (true) or manual tag-based (false)'
        required: false
        type: boolean
        default: true
      force-release:
        description: 'Force release type (empty for auto)'
        required: false
        type: string
        default: ''
      publish-to-pypi:
        description: 'Publish to PyPI after release'
        required: false
        type: boolean
        default: true
      pypi-package-name:
        description: 'PyPI package name'
        required: false
        type: string
        default: ''
      pypi-url:
        description: 'PyPI upload URL'
        required: false
        type: string
        default: 'https://upload.pypi.org/legacy/'
      run-tests:
        description: 'Run tests before release'
        required: false
        type: boolean
        default: true
    outputs:
      released:
        description: 'Whether a release was created'
        value: ${{ jobs.release.outputs.released }}
      version:
        description: 'The released version'
        value: ${{ jobs.release.outputs.version }}
      tag:
        description: 'The release tag'
        value: ${{ jobs.release.outputs.tag }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  attestations: write

jobs:
  # ============================================================================
  # Job 1: Run Tests Before Release
  # ============================================================================
  test:
    name: Pre-Release Tests
    runs-on: ubuntu-latest
    if: inputs.run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install ${{ inputs.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run tests
        run: |
          uv run pytest \
            --cov=${{ inputs.source-directory }} \
            --cov-report=term-missing \
            --cov-fail-under=${{ inputs.coverage-threshold }} \
            -v

      - name: Run type checker
        run: uv run basedpyright ${{ inputs.source-directory }}/

      - name: Run linter
        run: uv run ruff check ${{ inputs.source-directory }}/

  # ============================================================================
  # Job 2: Create Release (Semantic Release Mode)
  # ============================================================================
  release:
    name: Create Release
    needs: test
    if: always() && (needs.test.result == 'success' || needs.test.result == 'skipped')
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.semantic-release.outputs.released || steps.manual-release.outputs.released }}
      version: ${{ steps.semantic-release.outputs.version || steps.manual-release.outputs.version }}
      tag: ${{ steps.semantic-release.outputs.tag || steps.manual-release.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build package
        run: uv build

      # Semantic Release Mode
      - name: Python Semantic Release
        if: inputs.semantic-release
        id: semantic-release
        uses: python-semantic-release/python-semantic-release@v9.21.1
        with:
          github_token: ${{ github.token }}
          git_committer_name: "github-actions[bot]"
          git_committer_email: "github-actions[bot]@users.noreply.github.com"
          force: ${{ inputs.force-release }}

      - name: Upload to GitHub Release (Semantic)
        if: inputs.semantic-release && steps.semantic-release.outputs.released == 'true'
        uses: python-semantic-release/publish-action@v9.21.1
        with:
          github_token: ${{ github.token }}
          tag: ${{ steps.semantic-release.outputs.tag }}

      # Manual Release Mode
      - name: Manual Release
        if: "!inputs.semantic-release"
        id: manual-release
        run: |
          TAG="${{ github.event.inputs.tag || github.ref_name }}"
          VERSION="${TAG#v}"
          echo "released=true" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release (Manual)
        if: "!inputs.semantic-release"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.manual-release.outputs.tag }}
          generate_release_notes: true
          files: |
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Release Summary
        if: steps.semantic-release.outputs.released == 'true' || steps.manual-release.outputs.released == 'true'
        run: |
          VERSION="${{ steps.semantic-release.outputs.version || steps.manual-release.outputs.version }}"
          TAG="${{ steps.semantic-release.outputs.tag || steps.manual-release.outputs.tag }}"
          echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** $VERSION" >> $GITHUB_STEP_SUMMARY
          echo "**Tag:** $TAG" >> $GITHUB_STEP_SUMMARY

  # ============================================================================
  # Job 3: Publish to PyPI
  # ============================================================================
  publish-pypi:
    name: Publish to PyPI
    needs: release
    if: inputs.publish-to-pypi && (needs.release.outputs.released == 'true')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/${{ inputs.pypi-package-name }}/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release.outputs.tag }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install ${{ inputs.python-version }}

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        # Uses trusted publishing (OIDC) - configure at pypi.org/manage/account/publishing/
        run: uv publish --trusted-publishing always
        env:
          UV_PUBLISH_URL: ${{ inputs.pypi-url }}

      - name: PyPI Summary
        run: |
          echo "## PyPI Publication" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Published **${{ inputs.pypi-package-name }}** version **${{ needs.release.outputs.version }}** to PyPI" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[View on PyPI](https://pypi.org/project/${{ inputs.pypi-package-name }}/${{ needs.release.outputs.version }}/)" >> $GITHUB_STEP_SUMMARY
