# ============================================================================
# Reusable Python CI/CD Workflow
# ============================================================================
# This workflow should be placed in your organization's .github repository at:
#   .github/workflows/python-ci.yml
#
# Projects call this workflow using:
#   uses: ORG/.github/.github/workflows/python-ci.yml@main
#
# Features:
#   - Standard quality checks (tests, linting, type checking)
#   - LLM governance and assumption tag verification
#   - Optional SonarCloud integration
#   - Optional Codecov integration
#   - Security scanning (Bandit, Safety)
# ============================================================================

name: Reusable Python CI

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.12'
      coverage-threshold:
        description: 'Minimum code coverage percentage'
        required: false
        type: number
        default: 80
      source-directory:
        description: 'Source code directory'
        required: false
        type: string
        default: 'src'
      test-directory:
        description: 'Test directory'
        required: false
        type: string
        default: 'tests'
      enable-sonarcloud:
        description: 'Enable SonarCloud quality gate'
        required: false
        type: boolean
        default: false
      sonarcloud-organization:
        description: 'SonarCloud organization'
        required: false
        type: string
        default: ''
      sonarcloud-project-key:
        description: 'SonarCloud project key'
        required: false
        type: string
        default: ''
      enable-codecov:
        description: 'Enable Codecov uploads'
        required: false
        type: boolean
        default: false
      run-integration-tests:
        description: 'Run integration tests'
        required: false
        type: boolean
        default: true
      run-security-tests:
        description: 'Run security tests'
        required: false
        type: boolean
        default: true
      fail-on-llm-tags:
        description: 'Fail if LLM debt tags found'
        required: false
        type: boolean
        default: false
    secrets:
      SONAR_TOKEN:
        description: 'SonarCloud token'
        required: false
      CODECOV_TOKEN:
        description: 'Codecov token'
        required: false

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  # ============================================================================
  # Job 1: Standard Quality Checks
  # ============================================================================
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    outputs:
      coverage-artifact: coverage-reports

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Run Ruff formatter check
        run: |
          echo "::group::Ruff Formatting"
          uv run ruff format --check ${{ inputs.source-directory }}/ ${{ inputs.test-directory }}/ || {
            echo "::error::Code formatting issues detected. Run 'uv run ruff format ${{ inputs.source-directory }}/ ${{ inputs.test-directory }}/' to fix."
            exit 1
          }
          echo "::endgroup::"

      - name: Run Ruff linter
        run: |
          echo "::group::Ruff Linting"
          uv run ruff check ${{ inputs.source-directory }}/ ${{ inputs.test-directory }}/ --output-format=github
          echo "::endgroup::"

      - name: Run BasedPyright type checker
        run: |
          echo "::group::BasedPyright Type Checking"
          uv run basedpyright ${{ inputs.source-directory }}/ || {
            echo "::warning::Type checking found issues"
          }
          echo "::endgroup::"

      - name: Run unit tests with coverage
        run: |
          echo "::group::Unit Test Execution"
          uv run pytest \
            -m "unit or not (integration or security or slow)" \
            --cov=${{ inputs.source-directory }} \
            --cov-report=xml:coverage-unit.xml \
            --cov-report=term-missing \
            --cov-branch \
            -v
          echo "::endgroup::"

      - name: Run integration tests with coverage
        if: inputs.run-integration-tests
        run: |
          echo "::group::Integration Test Execution"
          uv run pytest \
            -m "integration" \
            --cov=${{ inputs.source-directory }} \
            --cov-report=xml:coverage-integration.xml \
            --cov-report=term-missing \
            --cov-branch \
            --cov-append \
            -v || echo "No integration tests found or all skipped"
          echo "::endgroup::"

      - name: Run security tests with coverage
        if: inputs.run-security-tests
        run: |
          echo "::group::Security Test Execution"
          uv run pytest \
            -m "security" \
            --cov=${{ inputs.source-directory }} \
            --cov-report=xml:coverage-security.xml \
            --cov-report=term-missing \
            --cov-branch \
            --cov-append \
            -v || echo "No security tests found or all skipped"
          echo "::endgroup::"

      - name: Generate combined coverage report
        run: |
          echo "::group::Combined Coverage"
          uv run coverage combine --keep || true
          uv run coverage xml -o coverage.xml
          uv run coverage html
          uv run coverage report --fail-under=${{ inputs.coverage-threshold }}
          echo "::endgroup::"

      - name: Security scan with Bandit
        run: |
          echo "::group::Bandit Security Scan"
          uv run bandit -r ${{ inputs.source-directory }}/ -f json -o bandit-report.json || {
            echo "::warning::Security issues detected"
            cat bandit-report.json
          }
          echo "::endgroup::"

      - name: Dependency vulnerability scan
        run: |
          echo "::group::Safety Dependency Scan"
          # Export requirements and scan
          uv pip compile pyproject.toml -o requirements.txt
          uv run safety check -r requirements.txt || {
            echo "::warning::Vulnerable dependencies detected"
          }
          echo "::endgroup::"

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            coverage-*.xml
            htmlcov/
          retention-days: 7

      - name: Upload coverage to Codecov
        if: inputs.enable-codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: python-${{ inputs.python-version }}
          name: combined-coverage
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # ============================================================================
  # Job 2: LLM Governance Checks
  # ============================================================================
  llm-governance:
    name: LLM Governance & Assumption Verification
    runs-on: ubuntu-latest
    timeout-minutes: 15

    outputs:
      rad-tags: ${{ steps.check-tags.outputs.rad_tags }}
      llm-tags: ${{ steps.check-tags.outputs.llm_tags }}
      total-tags: ${{ steps.check-tags.outputs.total_tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Check for unverified assumption tags
        id: check-tags
        run: |
          echo "::group::Scanning for Unverified Assumption Tags"

          # Check for RAD tags (Layer 1: Production Runtime Risks)
          CRITICAL_TAGS=$(grep -r "#CRITICAL" --include="*.py" ${{ inputs.source-directory }}/ 2>/dev/null | wc -l || echo "0")
          ASSUME_TAGS=$(grep -r "#ASSUME" --include="*.py" ${{ inputs.source-directory }}/ 2>/dev/null | wc -l || echo "0")
          EDGE_TAGS=$(grep -r "#EDGE" --include="*.py" ${{ inputs.source-directory }}/ 2>/dev/null | wc -l || echo "0")

          # Check for LLM debt tags (Layer 2: LLM Development Debt)
          LLM_MOCK=$(grep -r "#LLM-MOCK" --include="*.py" ${{ inputs.source-directory }}/ 2>/dev/null | wc -l || echo "0")
          LLM_PLACEHOLDER=$(grep -r "#LLM-PLACEHOLDER" --include="*.py" ${{ inputs.source-directory }}/ 2>/dev/null | wc -l || echo "0")
          LLM_LOGIC=$(grep -r "#LLM-LOGIC" --include="*.py" ${{ inputs.source-directory }}/ 2>/dev/null | wc -l || echo "0")
          LLM_SCAFFOLD=$(grep -r "#LLM-SCAFFOLD" --include="*.py" ${{ inputs.source-directory }}/ 2>/dev/null | wc -l || echo "0")
          LLM_INFERRED=$(grep -r "#LLM-INFERRED" --include="*.py" ${{ inputs.source-directory }}/ 2>/dev/null | wc -l || echo "0")
          LLM_TEST_FIRST=$(grep -r "#LLM-TEST-FIRST" --include="*.py" ${{ inputs.source-directory }}/ 2>/dev/null | wc -l || echo "0")

          TOTAL_RAD=$((CRITICAL_TAGS + ASSUME_TAGS))
          TOTAL_LLM=$((LLM_MOCK + LLM_PLACEHOLDER + LLM_LOGIC + LLM_SCAFFOLD + LLM_INFERRED + LLM_TEST_FIRST))
          TOTAL_TAGS=$((TOTAL_RAD + TOTAL_LLM))

          echo "rad_tags=$TOTAL_RAD" >> $GITHUB_OUTPUT
          echo "llm_tags=$TOTAL_LLM" >> $GITHUB_OUTPUT
          echo "total_tags=$TOTAL_TAGS" >> $GITHUB_OUTPUT

          echo "### Assumption Tag Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Layer 1 (Production Runtime Risks):**" >> $GITHUB_STEP_SUMMARY
          echo "- #CRITICAL tags: $CRITICAL_TAGS" >> $GITHUB_STEP_SUMMARY
          echo "- #ASSUME tags: $ASSUME_TAGS" >> $GITHUB_STEP_SUMMARY
          echo "- #EDGE tags: $EDGE_TAGS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Layer 2 (LLM Development Debt):**" >> $GITHUB_STEP_SUMMARY
          echo "- #LLM-MOCK: $LLM_MOCK" >> $GITHUB_STEP_SUMMARY
          echo "- #LLM-PLACEHOLDER: $LLM_PLACEHOLDER" >> $GITHUB_STEP_SUMMARY
          echo "- #LLM-LOGIC: $LLM_LOGIC" >> $GITHUB_STEP_SUMMARY
          echo "- #LLM-SCAFFOLD: $LLM_SCAFFOLD" >> $GITHUB_STEP_SUMMARY
          echo "- #LLM-INFERRED: $LLM_INFERRED" >> $GITHUB_STEP_SUMMARY
          echo "- #LLM-TEST-FIRST: $LLM_TEST_FIRST" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Total unverified tags: $TOTAL_TAGS**" >> $GITHUB_STEP_SUMMARY

          if [ "$TOTAL_RAD" -gt 0 ]; then
            echo "::error::Found $TOTAL_RAD unverified production risk tags (#CRITICAL, #ASSUME)"
          fi

          if [ "$TOTAL_LLM" -gt 0 ]; then
            echo "::warning::Found $TOTAL_LLM unverified LLM debt tags"
          fi

          echo "::endgroup::"

      - name: Block PR if critical tags found
        if: steps.check-tags.outputs.rad_tags > 0
        run: |
          echo "::error::❌ PR blocked: Found ${{ steps.check-tags.outputs.rad_tags }} unverified production risk tags"
          echo ""
          echo "Please verify and remove these tags before merging:"
          grep -rn "#CRITICAL\|#ASSUME" --include="*.py" ${{ inputs.source-directory }}/ || true
          echo ""
          echo "See CLAUDE.md for verification workflow"
          exit 1

      - name: Fail on LLM tags (if configured)
        if: inputs.fail-on-llm-tags && steps.check-tags.outputs.llm_tags > 0
        run: |
          echo "::error::❌ PR blocked: Found ${{ steps.check-tags.outputs.llm_tags }} LLM debt tags"
          echo ""
          echo "Please address LLM debt before merging:"
          grep -rn "#LLM-" --include="*.py" ${{ inputs.source-directory }}/ || true
          exit 1

      - name: Detect LLM anti-patterns
        run: |
          echo "::group::LLM Anti-Pattern Detection"

          # Hardcoded localhost/URLs
          echo "Checking for hardcoded localhost/URLs..."
          if grep -rE "(localhost|127\.0\.0\.1|http://|https://)" --include="*.py" ${{ inputs.source-directory }}/ | \
             grep -v "#LLM-PLACEHOLDER" | grep -v "^[[:space:]]*#"; then
            echo "::warning::Found hardcoded URLs without #LLM-PLACEHOLDER tag"
          fi

          # Hardcoded secrets patterns
          echo "Checking for potential hardcoded secrets..."
          if grep -rE "(api_key|password|secret|token)\s*=\s*[\"'][^\"']+[\"']" --include="*.py" ${{ inputs.source-directory }}/ | \
             grep -v "#LLM-PLACEHOLDER" | grep -v "^[[:space:]]*#"; then
            echo "::error::Potential hardcoded secret detected"
            exit 1
          fi

          # Magic numbers
          echo "Checking for magic numbers..."
          MAGIC_NUMBERS=$(grep -rE "\b[0-9]{2,}\b" --include="*.py" ${{ inputs.source-directory }}/ | \
                          grep -v "#LLM-PLACEHOLDER" | \
                          grep -v "^[[:space:]]*#" | \
                          wc -l || echo "0")

          if [ "$MAGIC_NUMBERS" -gt 10 ]; then
            echo "::warning::Found $MAGIC_NUMBERS potential magic numbers without constants"
          fi

          echo "::endgroup::"

  # ============================================================================
  # Job 3: SonarCloud Quality Gate (Optional)
  # ============================================================================
  sonarcloud-quality-gate:
    name: SonarCloud Quality Gate
    runs-on: ubuntu-latest
    needs: [quality-checks]
    if: inputs.enable-sonarcloud
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ inputs.sonarcloud-organization }}
            -Dsonar.projectKey=${{ inputs.sonarcloud-project-key }}

      - name: Wait for Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        id: quality-gate

      - name: Quality Gate Result
        run: |
          echo "::group::Quality Gate Status"
          echo "Quality Gate Status: ${{ steps.quality-gate.outputs.quality-gate-status }}"
          echo "View detailed results: https://sonarcloud.io/project/overview?id=${{ inputs.sonarcloud-project-key }}"
          echo "::endgroup::"

      - name: Block PR if quality gate fails
        if: steps.quality-gate.outputs.quality-gate-status == 'FAILED'
        run: |
          echo "::error::❌ Quality Gate FAILED"
          echo ""
          echo "SonarQube quality gate did not pass. Please fix the issues:"
          echo "- Review issues at: https://sonarcloud.io/project/overview?id=${{ inputs.sonarcloud-project-key }}"
          echo "- Fix all BLOCKER and CRITICAL issues"
          echo "- Ensure test coverage ≥ ${{ inputs.coverage-threshold }}%"
          echo "- Reduce code duplication"
          exit 1

  # ============================================================================
  # Summary Job
  # ============================================================================
  ci-summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [quality-checks, llm-governance]
    if: always()

    steps:
      - name: Generate final summary
        run: |
          echo "### CI Pipeline Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All governance layers checked:" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Code Quality Checks" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ LLM Governance Validation" >> $GITHUB_STEP_SUMMARY
          if [ "${{ inputs.enable-sonarcloud }}" == "true" ]; then
            echo "- ✅ SonarCloud Quality Gate" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Status: ${{ job.status }}**" >> $GITHUB_STEP_SUMMARY
