{%- if cookiecutter.include_fuzzing == "yes" -%}
# ClusterFuzzLite Project Configuration
# https://google.github.io/clusterfuzzlite/

# Python fuzzing configuration
language: python

# Build mode for fuzzing
# - coverage: For measuring fuzzing coverage
# - address: For detecting memory safety issues
# - undefined: For detecting undefined behavior
main_repo: https://github.com/{{ cookiecutter.github_org_or_user }}/{{ cookiecutter.github_repo_name }}.git
{%- endif %}
